export const ADD_BURGER_FILLING = "ADD_BURGER_FILLING";
export const ADD_BURGER_BUN = "ADD_BURGER_BUN";
export const DELETE_BURGER_FILLING = "DELETE_BURGER_FILLING";
export const REPLACE_BURGER_FILLING = "REPLCAE_BURGER_STUFFING";
export const ERASE_CONSTRUCTOR = "ERASE_CONSTRUCTOR";
